source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SourceKitPod_Example', :exclusive => true do
  pod "SourceKitPod", :path => "../"
end

target 'SourceKitPod_Tests', :exclusive => true do
  pod "SourceKitPod", :path => "../"

  
end
